<!DOCTYPE html>
<html lang="fr" prefix="og: https://ogp.me/ns#">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Une courte phrase qui décrit ce que fait votre page" />
      <meta name="keywords" content="Une série de mots clés repr'sentants les sujets principaux de votre site ou de votre page" />
      <meta name="author" content="Azu" />
      <meta name="referrer" content="origin" />
      <meta property="og:title" content="Le titre de la page" />
      <meta property="og:type" content="article" />
      <meta property="og:url" content="https://www.imdb.com/title/tt0117500/" />
      <meta property="og:image" content="https://ia.media-imdb.com/images/rock.jpg" />
      <meta property="og:description" content="La description" />
      <meta property="og:locale" content="fr_FR" />
      <meta property="og:site_name" content="Le nom du site" />
      <title>Titre de la page</title>
      <link rel="stylesheet" href="assets/style/css/style.css">
    </head>
    <body>
        <form action="defense.php" method="POST">
            <fieldset>
                <label for="username">Pseudo</label>
                <input type="text" name="username"/>
            </fieldset>
            <fieldset>
                <label for="email">Email</label>
                <input type="email" name="email"/>
            </fieldset>
            <fieldset>
                <label for="password">Mot de passe</label>
                <input type="password" name="password"/>
            </fieldset>
            <input type="submit" name="submit" value="Envoyer"/>
        </form>
    </body>
</html>

